package com.example.pickuplines.DataClasses

data class PickupLine(val line: String, val category: String)

object PickupLinesData {
    val badLines = listOf(
        PickupLine("Are you Google? Because you have everything I’ve been searching for.", "Bad"),
        PickupLine("I must be a snowflake, because I’ve fallen for you.", "Bad"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Bad"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Bad"),
        PickupLine("Do you like raisins? No? How about a date?", "Bad"),
        PickupLine("I must be a beaver, because I’m dying for your wood.", "Bad"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Bad"),
        PickupLine("Are you French? Because Eiffel for you.", "Bad"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Bad"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Bad"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Bad"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Bad"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Bad"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Bad"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Bad"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Bad"),
        PickupLine("Are you a mirror? Because I can see myself in your eyes.", "Bad"),
        PickupLine("Do you have a name, or can I call you mine?", "Bad"),
        PickupLine("You must be made of copper and tellurium because you're Cu-Te.", "Bad"),
        PickupLine("Are you a dictionary? Because you’re full of definitions.", "Bad"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Bad"),
        PickupLine("Do you like Star Wars? Because Yoda one for me.", "Bad"),
        PickupLine("I can’t seem to find my keys. Can I check your purse?", "Bad"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Bad"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Bad"),
        PickupLine("Are you a cake? Because I want a piece of you.", "Bad"),
        PickupLine("If I were a fruit, I’d be a fineapple.", "Bad"),
        PickupLine("Is your name Ariel? Because we mermaid for each other.", "Bad"),
        PickupLine("Do you have cheese? Because you’re gouda enough for me.", "Bad"),
        PickupLine("I’ve been reading a book on anti-gravity, and it’s impossible to put down… much like you.", "Bad"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Bad"),
        PickupLine("You must be a magician, because whenever I look at you, everyone else disappears.", "Bad"),
        PickupLine("Are you a parking ticket? Because you’ve got fine written all over you.", "Bad"),
        PickupLine("Do you have a map? Because I’m lost in your eyes.", "Bad"),
        PickupLine("Are you a snowstorm? Because you’re making my heart race.", "Bad"),
        PickupLine("Are you a volcano? Because you’re about to erupt with love.", "Bad"),
        PickupLine("If I were a vegetable, I’d be a cute-cumber.", "Bad"),
        PickupLine("Are you a Wi-Fi signal? Because I’m feeling a connection.", "Bad"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Bad"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Bad"),
        PickupLine("You must be a time traveler, because I can see you in my future.", "Bad"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Bad"),
        PickupLine("Are you French? Because Eiffel for you.", "Bad"),
        PickupLine("I was blinded by your beauty... I’m going to need your name and number for insurance purposes.", "Bad"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Bad")
    )

    val loveLines = listOf(
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Love"),
        PickupLine("Do you have a name, or can I call you mine?", "Love"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Love"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Love"),
        PickupLine("I’m not a genie, but I can make your dreams come true.", "Love"),
        PickupLine("I must be a snowflake, because I’ve fallen for you.", "Love"),
        PickupLine("Are you French? Because Eiffel for you.", "Love"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Love"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Love"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Love"),
        PickupLine("Are you an angel? Because heaven is missing one.", "Love"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Love"),
        PickupLine("Are you made of copper and tellurium? Because you’re Cu-Te.", "Love"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Love"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Love"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Love"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Love"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Love"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Love"),
        PickupLine("Are you French? Because Eiffel for you.", "Love"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Love"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Love"),
        PickupLine("I can’t stop thinking about you.", "Love"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Love"),
        PickupLine("If I were a cat, I’d spend all 9 lives with you.", "Love"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Love"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Love"),
        PickupLine("You must be a magician, because whenever I look at you, everyone else disappears.", "Love"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Love"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Love"),
        PickupLine("Is your name Ariel? Because we mermaid for each other.", "Love"),
        PickupLine("Do you have a map? I keep getting lost in your eyes.", "Love"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Love"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Love"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Love"),
        PickupLine("You must be a magician, because every time I look at you, everyone else disappears.", "Love"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Love")
    )

    val cuteLines = listOf(
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Cute"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Cute"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Cute"),
        PickupLine("If I were a cat, I’d spend all 9 lives with you.", "Cute"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Cute"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Cute"),
        PickupLine("Are you made of copper and tellurium? Because you’re Cu-Te.", "Cute"),
        PickupLine("You must be a magician, because every time I look at you, everyone else disappears.", "Cute"),
        PickupLine("Do you have a name, or can I call you mine?", "Cute"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Cute"),
        PickupLine("Are you a sunbeam? Because you light up my life.", "Cute"),
        PickupLine("Are you a unicorn? Because you’re magical.", "Cute"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Cute"),
        PickupLine("If you were a vegetable, you’d be a cute-cumber.", "Cute"),
        PickupLine("Are you a keyboard? Because you’re just my type.", "Cute"),
        PickupLine("You must be a wizard because whenever I look at you, everyone else disappears.", "Cute"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Cute"),
        PickupLine("Is your name Ariel? Because we mermaid for each other.", "Cute"),
        PickupLine("Are you a pizza? Because you’re hot and I want a slice.", "Cute"),
        PickupLine("Are you a painting? Because every time I look at you, I feel something new.", "Cute"),
        PickupLine("Are you a rainbow? Because you’re a sign of beauty and hope.", "Cute"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Cute"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Cute"),
        PickupLine("Are you an angel? Because heaven is missing one.", "Cute"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Cute"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Cute"),
        PickupLine("Is your name Ariel? Because we mermaid for each other.", "Cute"),
        PickupLine("Are you French? Because Eiffel for you.", "Cute"),
        PickupLine("Are you a picture? Because you’re worth a thousand words.", "Cute"),
        PickupLine("Are you a knight? Because you’ve swept me off my feet.", "Cute"),
        PickupLine("Are you a snowstorm? Because you’re making my heart race.", "Cute"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Cute"),
        PickupLine("You must be a camera, because every time I look at you, I smile.", "Cute"),
        PickupLine("Are you a firework? Because you light up my life.", "Cute")
    )


    val cleverLines = listOf(
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Clever"),
        PickupLine("Do you have a map? I keep getting lost in your eyes.", "Clever"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Clever"),
        PickupLine("Are you a 45-degree angle? Because you’re acute-y.", "Clever"),
        PickupLine("You must be made of copper and tellurium because you're Cu-Te.", "Clever"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Clever"),
        PickupLine("Are you an angel? Because heaven is missing one.", "Clever"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Clever"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Clever"),
        PickupLine("If you were a vegetable, you’d be a cute-cumber.", "Clever"),
        PickupLine("Are you made of uranium? Because you’re 92 protons of perfection.", "Clever"),
        PickupLine("If you were a fruit, you’d be a fineapple.", "Clever"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Clever"),
        PickupLine("You must be a campfire, because you're hot and I want s’more.", "Clever"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Clever"),
        PickupLine("Are you a keyboard? Because you're just my type.", "Clever"),
        PickupLine("Are you a beaver? Because daaaaam.", "Clever"),
        PickupLine("Are you an iPhone? Because you’re making my heart race.", "Clever"),
        PickupLine("Are you a lion? Because you’re roaring with beauty.", "Clever"),
        PickupLine("Are you a bank loan? Because you have my interest.", "Clever"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Clever"),
        PickupLine("Are you a Wi-Fi signal? Because I’m feeling a connection.", "Clever"),
        PickupLine("Is your dad a boxer? Because you’re a knockout.", "Clever"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Clever"),
        PickupLine("Are you a painter? Because you just drew me in.", "Clever"),
        PickupLine("Are you a compass? Because I keep getting lost in your eyes.", "Clever"),
        PickupLine("Are you a snowstorm? Because you make my heart race.", "Clever"),
        PickupLine("Is your name Ariel? Because we mermaid for each other.", "Clever"),
        PickupLine("Are you a flower? Because you’re blooming with beauty.", "Clever"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Clever"),
        PickupLine("Are you a mountain? Because I can’t get over you.", "Clever"),
        PickupLine("Do you have a mirror in your pocket? Because I see myself in your pants.", "Clever"),
        PickupLine("Are you a cucumber? Because you’re cool and I’m pickled.", "Clever"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Clever"),
        PickupLine("Do you know what would look great on you? Me.", "Clever"),
        PickupLine("Are you a planet? Because your gravity keeps pulling me in.", "Clever"),
        PickupLine("Are you a volcano? Because I’m lava you.", "Clever"),
        PickupLine("Are you an alien? Because you’ve abducted my heart.", "Clever"),
        PickupLine("Are you a mirror? Because I can see myself in your future.", "Clever"),
        PickupLine("Are you made of steel? Because I’m magnetically drawn to you.", "Clever"),
        PickupLine("Is your name Summer? Because you’re hot and I’m falling for you.", "Clever"),
        PickupLine("Are you a game of chess? Because you’re making all my moves.", "Clever"),
        PickupLine("Are you the moon? Because you’re lighting up my world.", "Clever"),
        PickupLine("Are you a cup of coffee? Because you’re brewing up my feelings.", "Clever"),
        PickupLine("Is your name Watson? Because you’ve got the solution to my heart’s problem.", "Clever"),
        PickupLine("Are you a magician? Because you just made my heart disappear.", "Clever"),
        PickupLine("Are you a starfish? Because you’re one in a million.", "Clever")
    )

    val dirtyLines = listOf(
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Dirty"),
        PickupLine("Are you a broom? Because you just swept me off my feet.", "Dirty"),
        PickupLine("Are you a fire? Because you’re hot and I’m burned.", "Dirty"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Dirty"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Dirty"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Dirty"),
        PickupLine("Are you a mirror? Because I can see myself in your eyes.", "Dirty"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Dirty"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Dirty"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Dirty"),
        PickupLine("Are you a magnet? Because I’m drawn to you.", "Dirty"),
        PickupLine("Are you a lightbulb? Because you brighten up my day.", "Dirty"),
        PickupLine("Are you a dictionary? Because you’re adding meaning to my life.", "Dirty"),
        PickupLine("Are you a spaceship? Because your beauty is out of this world.", "Dirty"),
        PickupLine("Are you a wifi signal? Because I’m feeling a connection.", "Dirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Dirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Dirty"),
        PickupLine("Are you a flower? Because you’re blooming with beauty.", "Dirty"),
        PickupLine("Are you an angel? Because heaven is missing one.", "Dirty"),
        PickupLine("Are you a storm? Because you make my heart race.", "Dirty"),
        PickupLine("Are you a volcano? Because I’m lava you.", "Dirty"),
        PickupLine("Are you a cup of coffee? Because you’re brewing up my feelings.", "Dirty"),
        PickupLine("Are you an artist? Because you just drew me in.", "Dirty"),
        PickupLine("Are you a math problem? Because I’m trying to solve for your heart.", "Dirty"),
        PickupLine("Are you a planet? Because your gravity is pulling me in.", "Dirty"),
        PickupLine("Are you a diamond? Because you’re precious.", "Dirty"),
        PickupLine("Are you a giraffe? Because I’m falling for you from a great height.", "Dirty"),
        PickupLine("Are you a mirror? Because I can see myself with you.", "Dirty"),
        PickupLine("Are you a raccoon? Because I’m trash for you.", "Dirty"),
        PickupLine("Are you a banana? Because I find you a-peeling.", "Dirty"),
        PickupLine("Are you a lollipop? Because I’m addicted to you.", "Dirty"),
        PickupLine("Are you a pizza? Because you’ve got me craving for you.", "Dirty"),
        PickupLine("Are you a jellybean? Because you’re sweet and I want more.", "Dirty"),
        PickupLine("Are you a shark? Because I’m hooked on you.", "Dirty"),
        PickupLine("Are you an astronaut? Because I’m lost in your eyes.", "Dirty"),
        PickupLine("Are you a banana split? Because you’re splitting my heart in two.", "Dirty"),
        PickupLine("Are you a cupcake? Because you’re sweet and irresistible.", "Dirty"),
        PickupLine("Are you a tornado? Because you just blew me away.", "Dirty"),
        PickupLine("Are you a vampire? Because I’m falling for you.", "Dirty"),
        PickupLine("Are you a shark? Because I’m hooked on you.", "Dirty"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Dirty")
    )

    val foodLines = listOf(
        PickupLine("Are you a pizza? Because you’re hot and I want a slice.", "Food"),
        PickupLine("Do you like hamburgers? Because I can’t get enough of you.", "Food"),
        PickupLine("Are you French fries? Because I’m dipping for you.", "Food"),
        PickupLine("Are you a donut? Because I’m hooked on you.", "Food"),
        PickupLine("Are you a taco? Because you’re bringing the heat.", "Food"),
        PickupLine("Do you like spaghetti? Because I can’t stop twirling around you.", "Food"),
        PickupLine("Are you a cookie? Because you’re sweet and I want more.", "Food"),
        PickupLine("Is your name Nutella? Because you spread sweetness wherever you go.", "Food"),
        PickupLine("If you were a vegetable, you’d be a cute-cumber.", "Food"),
        PickupLine("Are you a sandwich? Because I can’t stop putting you on my mind.", "Food"),
        PickupLine("Are you a strawberry? Because you’re berry sweet.", "Food"),
        PickupLine("Are you ice cream? Because you’re making me melt.", "Food"),
        PickupLine("Are you a cupcake? Because you’re sweet and irresistible.", "Food"),
        PickupLine("Do you like apples? Because I’m falling for you.", "Food"),
        PickupLine("Are you a banana? Because I find you a-peeling.", "Food"),
        PickupLine("Are you a pancake? Because I’m flipping out over you.", "Food"),
        PickupLine("Are you a hot dog? Because you’re the wurst!", "Food"),
        PickupLine("Are you a mango? Because I’m mad about you.", "Food"),
        PickupLine("Are you a pickle? Because you’re one in a million.", "Food"),
        PickupLine("Are you chocolate? Because you make everything better.", "Food"),
        PickupLine("Are you ketchup? Because you complete me.", "Food"),
        PickupLine("Are you a cheeseburger? Because you’re flipping my heart upside down.", "Food"),
        PickupLine("Are you a pineapple? Because you make everything sweet.", "Food"),
        PickupLine("Are you honey? Because you’re so sweet.", "Food"),
        PickupLine("Are you a watermelon? Because you’re making my heart race.", "Food"),
        PickupLine("Are you a pancake? Because I’m flipping out over you.", "Food"),
        PickupLine("Are you chocolate cake? Because you’re rich and delicious.", "Food"),
        PickupLine("Are you a smoothie? Because you’re sweet and refreshing.", "Food"),
        PickupLine("Are you a strawberry milkshake? Because you’re berry sweet.", "Food"),
        PickupLine("Are you cereal? Because you make my morning perfect.", "Food"),
        PickupLine("Are you a caramel apple? Because you’re a treat.", "Food"),
        PickupLine("Are you a muffin? Because you’re muffin like anyone else.", "Food"),
        PickupLine("Are you a fruit salad? Because you’re full of sweetness.", "Food"),
        PickupLine("Are you a croissant? Because you’re flaky and delicious.", "Food"),
        PickupLine("Are you a sandwich? Because I can’t stop putting you on my mind.", "Food"),
        PickupLine("Are you peanut butter? Because I’m nuts about you.", "Food"),
        PickupLine("Are you a cherry? Because you’re the sweetest part of the fruit salad.", "Food"),
        PickupLine("Are you a cookie? Because I want to dunk you in my milk.", "Food"),
        PickupLine("Are you a cupcake? Because you’ve got me hooked.", "Food"),
        PickupLine("Are you a jelly bean? Because I want to eat you up.", "Food")
    )


    val cheesyLines = listOf(
        PickupLine("Are you French? Because Eiffel for you.", "Cheesy"),
        PickupLine("Is your name Chapstick? Because you’re da balm.", "Cheesy"),
        PickupLine("Are you cheese? Because you’re gouda enough for me.", "Cheesy"),
        PickupLine("Are you a tortilla? Because I’m falling for you and I want to wrap you up.", "Cheesy"),
        PickupLine("Are you a slice of cheese? Because you’re making my heart melt.", "Cheesy"),
        PickupLine("Are you cheddar? Because you’re making me melt.", "Cheesy"),
        PickupLine("Are you a sandwich? Because you’re making me feel all stuffed.", "Cheesy"),
        PickupLine("Are you a quesadilla? Because you’re making my heart hot and crispy.", "Cheesy"),
        PickupLine("Are you a piece of cake? Because you’re sweet and I want a piece.", "Cheesy"),
        PickupLine("If you were a cheese, you’d be Feta, because you’re so feta-tastic!", "Cheesy"),
        PickupLine("Are you mozzarella? Because you make everything cheesy.", "Cheesy"),
        PickupLine("Are you a cracker? Because you’re making my heart crumble.", "Cheesy"),
        PickupLine("Are you a salad? Because you’re making me feel fresh.", "Cheesy"),
        PickupLine("Are you a nacho? Because you’re nacho average girl.", "Cheesy"),
        PickupLine("Are you an avocado? Because I can’t guac without you.", "Cheesy"),
        PickupLine("Are you spaghetti? Because I’m falling for you, and I can’t seem to untangle myself.", "Cheesy"),
        PickupLine("Are you a taco? Because you’re bringing the heat.", "Cheesy"),
        PickupLine("Are you a muffin? Because I’m muffin without you.", "Cheesy"),
        PickupLine("Are you an omelet? Because I’m egg-cited to see you.", "Cheesy"),
        PickupLine("Are you whipped cream? Because you’re topping off my life.", "Cheesy"),
        PickupLine("Are you a pizza? Because you’ve got all the right toppings.", "Cheesy"),
        PickupLine("Are you a strawberry? Because you’re berry sweet.", "Cheesy"),
        PickupLine("Are you a pancake? Because I’m flipping out for you.", "Cheesy"),
        PickupLine("Are you a cupcake? Because you’re sweet and irresistible.", "Cheesy"),
        PickupLine("Are you a cherry? Because you’re the sweetest part of the fruit salad.", "Cheesy"),
        PickupLine("Are you peanut butter? Because I’m nuts about you.", "Cheesy"),
        PickupLine("Are you a watermelon? Because you’re making my heart race.", "Cheesy"),
        PickupLine("Are you hot sauce? Because you’re making me spicy.", "Cheesy"),
        PickupLine("Are you a donut? Because I’m hooked on you.", "Cheesy"),
        PickupLine("Are you a cookie? Because I’m craving you.", "Cheesy"),
        PickupLine("Are you a lemon? Because you’re making everything sour without you.", "Cheesy"),
        PickupLine("Are you a smoothie? Because you’re blending my heart.", "Cheesy"),
        PickupLine("Are you a nut? Because you’re cracking me up.", "Cheesy"),
        PickupLine("Are you ketchup? Because you complete me.", "Cheesy"),
        PickupLine("Are you a berry? Because I’m falling for you.", "Cheesy"),
        PickupLine("Are you butter? Because you’re on a roll.", "Cheesy"),
        PickupLine("Are you a potato? Because you’re smashing.", "Cheesy"),
        PickupLine("Are you a cherry pie? Because I’m ready to indulge.", "Cheesy"),
        PickupLine("Are you a sandwich? Because I’m falling for you between two slices.", "Cheesy"),
        PickupLine("Are you a fruit salad? Because you’re a bowl of sweet surprises.", "Cheesy"),
        PickupLine("Are you a coffee? Because I’m espresso-ing my love for you.", "Cheesy"),
        PickupLine("Are you a popcorn kernel? Because you make my heart pop!", "Cheesy"),
        PickupLine("Are you a cupcake? Because you’re sweet and baked to perfection.", "Cheesy"),
        PickupLine("Are you a hotdog? Because you make everything better.", "Cheesy"),
        PickupLine("Are you chocolate? Because you melt me.", "Cheesy"),
        PickupLine("Are you a potato chip? Because I can’t stop crunching on you.", "Cheesy"),
        PickupLine("Are you a cookie? Because I just want to break you into pieces.", "Cheesy"),
        PickupLine("Are you a smoothie? Because you’re mixing my emotions.", "Cheesy")
    )

    val funnyLines = listOf(
        PickupLine("Do you like Star Wars? Because Yoda one for me.", "Funny"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Funny"),
        PickupLine("If you were a vegetable, you’d be a cute-cumber.", "Funny"),
        PickupLine("Are you French? Because Eiffel for you.", "Funny"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Funny"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Funny"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Funny"),
        PickupLine("I must be a snowflake, because I’ve fallen for you.", "Funny"),
        PickupLine("Are you made of copper and tellurium? Because you’re Cu-Te.", "Funny"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Funny"),
        PickupLine("Are you an alien? Because your beauty is out of this world.", "Funny"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Funny"),
        PickupLine("Are you a vampire? Because you’ve sucked the life out of me.", "Funny"),
        PickupLine("Do you believe in love at first sight or should I walk by again?", "Funny"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Funny"),
        PickupLine("Are you a magnet? Because I’m drawn to you.", "Funny"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Funny"),
        PickupLine("Are you a keyboard? Because you're just my type.", "Funny"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Funny"),
        PickupLine("Are you a beaver? Because daaaaam.", "Funny"),
        PickupLine("Are you a lightbulb? Because you brighten up my world.", "Funny"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Funny"),
        PickupLine("Are you a chicken? Because you're eggs-tra special.", "Funny"),
        PickupLine("Are you a waffle? Because I’m falling for you, no syrup needed.", "Funny"),
        PickupLine("Are you a cloud? Because you’ve been raining on my parade.", "Funny"),
        PickupLine("Are you a pizza? Because you’re making me crave you.", "Funny"),
        PickupLine("Are you a cat? Because I’m feline good about you.", "Funny"),
        PickupLine("Are you a sunbeam? Because you light up my world.", "Funny"),
        PickupLine("Are you a bicycle? Because I want to ride with you.", "Funny"),
        PickupLine("Are you a keyboard? Because you’ve got all the right keys to my heart.", "Funny"),
        PickupLine("Are you an ice cream cone? Because you’re making me melt.", "Funny"),
        PickupLine("Are you a banana? Because I find you a-peeling.", "Funny"),
        PickupLine("Do you have a mirror in your pocket? Because I can see myself in your future.", "Funny"),
        PickupLine("Are you a watermelon? Because you’re making my heart race.", "Funny"),
        PickupLine("Are you a pillow? Because I want to cuddle up to you.", "Funny"),
        PickupLine("Are you a genie? Because you just granted my wish.", "Funny"),
        PickupLine("Are you a rocket? Because you’ve launched my heart into space.", "Funny"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Funny"),
        PickupLine("Are you a dragon? Because you’re fire-breathing hot.", "Funny"),
        PickupLine("Are you a rainbow? Because you’ve brightened my world.", "Funny"),
        PickupLine("Are you an oven? Because you're heating things up.", "Funny"),
        PickupLine("Are you a flower? Because you just bloomed in my heart.", "Funny"),
        PickupLine("Are you a piece of candy? Because I’m sweet on you.", "Funny"),
        PickupLine("Are you a car? Because I’m totally driven by you.", "Funny"),
        PickupLine("Are you a spider? Because you’ve got me tangled up in you.", "Funny"),
        PickupLine("Are you a dinosaur? Because you’re dino-mite!", "Funny"),
        PickupLine("Are you a parachute? Because I’ve fallen for you.", "Funny")
    )

    val romanticLines = listOf(
        PickupLine("Are you a star? Because your beauty lights up the night.", "Romantic"),
        PickupLine("Can I follow you home? Because my parents always told me to follow my dreams.", "Romantic"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Romantic"),
        PickupLine("You must be a magician, because whenever I look at you, everyone else disappears.", "Romantic"),
        PickupLine("I must be a snowflake, because I’ve fallen for you.", "Romantic"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Romantic"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Romantic"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Romantic"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Romantic"),
        PickupLine("I’ve got a case of love, and the only prescription is you.", "Romantic"),
        PickupLine("Are you a dream? Because I’ve been dreaming about you.", "Romantic"),
        PickupLine("You must be made of stardust, because you’re out of this world.", "Romantic"),
        PickupLine("I can’t imagine life without you.", "Romantic"),
        PickupLine("Are you the ocean? Because I can’t seem to get enough of you.", "Romantic"),
        PickupLine("I don’t need a map. I’m already lost in your eyes.", "Romantic"),
        PickupLine("You’re the peanut butter to my jelly.", "Romantic"),
        PickupLine("I didn’t believe in love at first sight, but that was before I met you.", "Romantic"),
        PickupLine("You are the reason I smile every day.", "Romantic"),
        PickupLine("Are you my soulmate? Because everything feels perfect when I’m with you.", "Romantic"),
        PickupLine("I’d cross the world just to see your smile.", "Romantic"),
        PickupLine("Every moment with you feels like a dream come true.", "Romantic"),
        PickupLine("I never thought love would find me, but then you walked into my life.", "Romantic"),
        PickupLine("When I’m with you, the world feels right.", "Romantic"),
        PickupLine("You make my heart beat faster every time I see you.", "Romantic"),
        PickupLine("I don’t need a reason to love you. I just do.", "Romantic"),
        PickupLine("With you by my side, I can conquer anything.", "Romantic"),
        PickupLine("Are you a rose? Because you’re blooming in my heart.", "Romantic"),
        PickupLine("You’re the rhythm in my heart.", "Romantic"),
        PickupLine("You complete me.", "Romantic"),
        PickupLine("Without you, I’m lost.", "Romantic"),
        PickupLine("Love isn’t about how many days, months, or years we’ve been together. It’s about how much we love each other every single day.", "Romantic"),
        PickupLine("You’re my happily ever after.", "Romantic"),
        PickupLine("With you, I’m home.", "Romantic"),
        PickupLine("You are my sunshine on a cloudy day.", "Romantic"),
        PickupLine("Are you a melody? Because you’re always playing in my heart.", "Romantic"),
        PickupLine("Your love is like a warm embrace that fills me with happiness.", "Romantic")
    )

    val sadLines = listOf(
        PickupLine("Are you a time traveler? Because I see you in my future, but I feel so lonely.", "Sad"),
        PickupLine("Is your name Google? Because you have all the answers to my sadness.", "Sad"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Sad"),
        PickupLine("I’m like a broken pencil… pointless without you.", "Sad"),
        PickupLine("My love for you is like pi, it’s never-ending.", "Sad"),
        PickupLine("Are you a calendar? Because my days are incomplete without you.", "Sad"),
        PickupLine("If love is a crime, I should be arrested.", "Sad"),
        PickupLine("I’d say you’re the one, but I’m too afraid of being wrong.", "Sad"),
        PickupLine("Are you a loan? Because you have my interest.", "Sad"),
        PickupLine("Do you like books? Because I can’t stop reading your eyes.", "Sad"),
        PickupLine("Are you a camera? Because every time I see you, I smile, even though my heart is broken.", "Sad"),
        PickupLine("You’re the reason I can’t stop crying.", "Sad"),
        PickupLine("My heart aches every time I think of you.", "Sad"),
        PickupLine("I don’t want to let go of you, but I know I must.", "Sad"),
        PickupLine("Even when you're not around, you’re all I think about.", "Sad"),
        PickupLine("You may not realize it, but you’re the best part of my day.", "Sad"),
        PickupLine("I’m stuck in this cycle of hope and heartbreak.", "Sad"),
        PickupLine("I miss you even when you're right here.", "Sad"),
        PickupLine("I’ve been loving you in silence.", "Sad"),
        PickupLine("You were once my everything, now I’m left with nothing.", "Sad"),
        PickupLine("Sometimes I wish I never met you, just so I wouldn’t have to feel this pain.", "Sad"),
        PickupLine("My heart is torn between holding on and letting go.", "Sad"),
        PickupLine("Even if you’re gone, I’ll keep holding on to you in my heart.", "Sad"),
        PickupLine("I thought I was over you, but your memory still haunts me.", "Sad"),
        PickupLine("I’m broken, but I keep pretending to be whole.", "Sad"),
        PickupLine("Every time I think I’m okay, something reminds me of you.", "Sad"),
        PickupLine("I wish you knew how much you mean to me.", "Sad"),
        PickupLine("It’s hard to move on when I’m still in love with you.", "Sad"),
        PickupLine("You’re the ghost that haunts my heart.", "Sad"),
        PickupLine("My heart is a puzzle, and you were the missing piece.", "Sad"),
        PickupLine("I’ll always love you, even from a distance.", "Sad"),
        PickupLine("It hurts to breathe without you.", "Sad"),
        PickupLine("I gave you my heart, but you didn’t take care of it.", "Sad"),
        PickupLine("I’ll love you even after you leave me behind.", "Sad"),
        PickupLine("It’s hard to let go of something you thought was forever.", "Sad"),
        PickupLine("Sometimes, loving you feels like a dream that never came true.", "Sad"),
        PickupLine("I’m lost without you.", "Sad")
    )


    val flirtyLines = listOf(
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Flirty"),
        PickupLine("If you were a vegetable, you’d be a cute-cumber.", "Flirty"),
        PickupLine("Do you have a name, or can I call you mine?", "Flirty"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Flirty"),
        PickupLine("Are you French? Because Eiffel for you.", "Flirty"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Flirty"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Flirty"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Flirty"),
        PickupLine("If I were a cat, I’d spend all 9 lives with you.", "Flirty"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Flirty"),
        PickupLine("You must be made of copper and tellurium, because you’re Cu-Te.", "Flirty"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Flirty"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Flirty"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Flirty"),
        PickupLine("Are you a campfire? Because you’re hot and I’m falling for you.", "Flirty"),
        PickupLine("Do you like coffee? Because I like you a latte.", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Flirty"),
        PickupLine("Are you a magician? Because every time I look at you, everyone else disappears.", "Flirty"),
        PickupLine("I’m not a photographer, but I can picture us together.", "Flirty"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Flirty"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Flirty"),
        PickupLine("Do you have a Band-Aid? Because I just scraped my knee falling for you.", "Flirty"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Flirty"),
        PickupLine("Are you a beaver? Because daaaaam.", "Flirty"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Flirty"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Flirty"),
        PickupLine("Are you French? Because Eiffel for you.", "Flirty"),
        PickupLine("Do you have a name, or can I call you mine?", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("Can I follow you home? Cause my parents always told me to follow my dreams.", "Flirty"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Flirty"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Flirty"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Flirty"),
        PickupLine("If you were a cat, you’d purrfect.", "Flirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Flirty"),
        PickupLine("Are you a bee? Because you’re the bee’s knees.", "Flirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Flirty"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Flirty"),
        PickupLine("You must be tired because you’ve been running through my mind all day.", "Flirty"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Flirty"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Flirty"),
        PickupLine("Are you a magician? Because every time I look at you, everyone else disappears.", "Flirty"),
        PickupLine("Do you like raisins? No? How about a date?", "Flirty"),
        PickupLine("Are you a park? Because I’m falling for you.", "Flirty"),
        PickupLine("You must be a magician because whenever I look at you, everyone else disappears.", "Flirty"),
        PickupLine("Are you a time traveler? Because I see you in my future.", "Flirty"),
        PickupLine("Is your name Google? Because you have all the answers to my questions.", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("Can I follow you home? Cause my parents always told me to follow my dreams.", "Flirty"),
        PickupLine("Are you French? Because Eiffel for you.", "Flirty"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Flirty"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Flirty"),
        PickupLine("Are you a light bulb? Because you brighten up my day.", "Flirty"),
        PickupLine("Are you a dictionary? Because you add meaning to my life.", "Flirty"),
        PickupLine("I must be a snowflake, because I’ve fallen for you.", "Flirty"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Flirty"),
        PickupLine("Do you have a map? Because I keep getting lost in your eyes.", "Flirty"),
        PickupLine("Is your name Google? Because you’ve got everything I’ve been searching for.", "Flirty"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Flirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Flirty"),
        PickupLine("Are you a beaver? Because daaaaam.", "Flirty"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Flirty"),
        PickupLine("Are you French? Because Eiffel for you.", "Flirty"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Flirty"),
        PickupLine("Are you a campfire? Because you’re hot and I want s’more.", "Flirty"),
        PickupLine("Do you like coffee? Because I like you a latte.", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("I must be a snowflake because I’ve fallen for you.", "Flirty"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Flirty"),
        PickupLine("You must be made of copper and tellurium, because you’re Cu-Te.", "Flirty"),
        PickupLine("Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.", "Flirty"),
        PickupLine("Are you a time traveler? Because I can see you in my future.", "Flirty"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Flirty"),
        PickupLine("Are you a star? Because your beauty lights up the night.", "Flirty"),
        PickupLine("Can I follow you home? Cause my parents always told me to follow my dreams.", "Flirty"),
        PickupLine("Do you believe in love at first sight, or should I walk by again?", "Flirty"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Flirty"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Flirty"),
        PickupLine("If you were a cat, you’d purrfect.", "Flirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Flirty"),
        PickupLine("Are you a bee? Because you’re the bee’s knees.", "Flirty"),
        PickupLine("Do you have a pencil? Because I want to erase your past and write our future.", "Flirty")
    )

    val classicLines = listOf(
        PickupLine("Is there a sparkle in your eye, or are you just happy to see me?", "Classic"),
        PickupLine("Excuse me, do you have a moment? Because I can't stop thinking about you.", "Classic"),
        PickupLine("Are you sitting on the F5 key? Because you’re refreshing.", "Classic"),
        PickupLine("You must be tired because you've been running through my mind all day.", "Classic"),
        PickupLine("Is there an airport nearby or is my heart taking off?", "Classic"),
        PickupLine("Do you have a map? I keep getting lost in your eyes.", "Classic"),
        PickupLine("Do you like to draw? Because I can’t stop sketching you in my mind.", "Classic"),
        PickupLine("Are you the moon? Because you light up my night.", "Classic"),
        PickupLine("Is your name Wi-Fi? Because I’m feeling a connection.", "Classic"),
        PickupLine("If I were to ask you out, would your answer be the same as the answer to this question?", "Classic"),
        PickupLine("Are you a candy bar? Because you're sweet and irresistible.", "Classic"),
        PickupLine("Are you a keyboard? Because you're just my type.", "Classic"),
        PickupLine("If I were a superhero, you’d be my sidekick because you’re always on my mind.", "Classic"),
        PickupLine("Are you a camera? Because every time I look at you, I smile.", "Classic"),
        PickupLine("Do you know what would look great on you? Me.", "Classic"),
        PickupLine("Is your dad a gardener? Because you’re a blooming beauty.", "Classic"),
        PickupLine("Are you made of gold? Because you're precious.", "Classic"),
        PickupLine("Are you a cupcake? Because you’re sweet and irresistible.", "Classic"),
        PickupLine("Are you an angel? Because I think I’ve finally found heaven.", "Classic"),
        PickupLine("If kisses were snowflakes, I’d send you a blizzard.", "Classic"),
        PickupLine("Is your name Chapstick? Because you’re da balm.", "Classic")
    )

    val complimentLines = listOf(
        PickupLine("You have the most beautiful smile I’ve ever seen.", "Compliment"),
        PickupLine("You must be a work of art, because every time I look at you, I’m amazed.", "Compliment"),
        PickupLine("Is it just me, or are we meant to be together?", "Compliment"),
        PickupLine("Your eyes are so captivating, I could get lost in them forever.", "Compliment"),
        PickupLine("If I could rearrange the alphabet, I’d put U and I together.", "Compliment"),
        PickupLine("You’re so sweet, you’re giving me a toothache.", "Compliment"),
        PickupLine("Are you a magician? Because whenever I look at you, everyone else disappears.", "Compliment"),
        PickupLine("You must be made of copper and tellurium because you’re Cu-Te.", "Compliment"),
        PickupLine("You’ve got the most amazing laugh.", "Compliment"),
        PickupLine("Is your name Google? Because you have everything I’ve been searching for.", "Compliment"),
        PickupLine("You’re the reason I smile every day.", "Compliment"),
        PickupLine("I can’t imagine my life without you in it.", "Compliment"),
        PickupLine("If beauty were a crime, you’d be serving a life sentence.", "Compliment"),
        PickupLine("Your voice is my favorite sound.", "Compliment"),
        PickupLine("You’re the best thing that’s ever happened to me.", "Compliment"),
        PickupLine("You make the world a better place just by being in it.", "Compliment"),
        PickupLine("I could spend forever looking at you and never get tired of it.", "Compliment"),
        PickupLine("You have a heart of gold, and I’m lucky to know you.", "Compliment"),
        PickupLine("If I had a flower for every time I thought of you, I could walk through my garden forever.", "Compliment"),
        PickupLine("Your smile brightens up even the darkest days.", "Compliment")
    )


}
